const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const LUGARES = [
    {
        nombre: "Parque Nacional Ciervo de los Pantanos",
        slug: "ciervo-pantanos",
        ubicacion: "Campana, Buenos Aires",
        lat: -34.2325,
        lng: -58.8517,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Silla", "Andador", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "500m senderos cortos",
        ruido: "Bajo",
        tiene_sombra: true,
        mejor_estacion: ["Primavera", "Otoño"],
        notas_honestas: "Ideal desde AMBA, humedales y naturaleza tranquila; calor fuerte verano, mejor entre semana.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        pet_friendly: false,
        imagenes: ["https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Museo Histórico Cornelio de Saavedra",
        slug: "museo-saavedra",
        ubicacion: "Crisólogo Larralde 6309, Saavedra, CABA",
        lat: -34.5574,
        lng: -58.5022,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Silla", "Andador", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "0m (estacionamiento prioritario)",
        ruido: "Bajo",
        tiene_sombra: true,
        mejor_estacion: ["Primavera", "Otoño"],
        notas_honestas: "Museo chico-mediano, se recorre tranquilo en menos de 2 horas; buena sombra y bancos, ideal tarde tranquila sin filas.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        pet_friendly: true,
        imagenes: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Cultura"
    },
    {
        nombre: "Museo Nacional de Ciencias Naturales",
        slug: "museo-ciencias-naturales",
        ubicacion: "Av. Ángel Gallardo 490, Recoleta, CABA",
        lat: -34.6051,
        lng: -58.4379,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Medio",
        movilidad: ["Silla", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: false,
        distancia_aprox: "100m entre salas",
        ruido: "Alto",
        tiene_sombra: true,
        mejor_estacion: ["Primavera", "Otoño"],
        notas_honestas: "Rampas y ascensores, pero varios pisos y mucha gente (familias, pibes); ideal elegir 1-2 salas para no saturarse.",
        fuente: "Comunitario",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1551392505-f4056032826e?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Cultura"
    },
    {
        nombre: "Museo de Arte Moderno de Buenos Aires",
        slug: "museo-moderno",
        ubicacion: "Av. San Juan 350, San Telmo, CABA",
        lat: -34.6212,
        lng: -58.3731,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Silla", "Andador", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "50m desde entrada",
        ruido: "Medio",
        tiene_sombra: true,
        mejor_estacion: ["Otoño", "Invierno"],
        notas_honestas: "Puerta automática, ascensores, espacio táctil con piezas 3D, info Braille y audiodescripciones; ambiente interior, re fuerte en accesibilidad de contenidos.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1506097425191-7ad538b29cef?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Cultura"
    },
    {
        nombre: "MALBA",
        slug: "malba",
        ubicacion: "Av. Figueroa Alcorta 3415, Palermo, CABA",
        lat: -34.577,
        lng: -58.403,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Silla", "Andador"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "50m circuito completo",
        ruido: "Medio",
        tiene_sombra: true,
        mejor_estacion: ["Otoño", "Invierno"],
        notas_honestas: "Rampas, escaleras mecánicas, ascensor; sillas disponibles en recepción. Compacto, ojo con fines de semana llenos.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Cultura"
    },
    {
        nombre: "BAM - Buenos Aires Museo",
        slug: "bam-buenos-aires-museo",
        ubicacion: "Defensa 187, Monserrat, CABA",
        lat: -34.611,
        lng: -58.371,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Medio",
        movilidad: ["Silla", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: false,
        distancia_aprox: "100m desde vereda",
        ruido: "Medio",
        tiene_sombra: true,
        mejor_estacion: ["Primavera", "Otoño"],
        notas_honestas: "Casco histórico (empedrado afuera), adentro renovado con señalética inclusiva; esfuerzo bajo una vez adentro.",
        fuente: "Comunitario",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Cultura"
    },
    {
        nombre: "Parque Nacional Iguazú",
        slug: "iguazu",
        ubicacion: "Puerto Iguazú, Misiones",
        lat: -25.6953,
        lng: -54.4367,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo-Medio",
        movilidad: ["Silla", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: false,
        distancia_aprox: "100-300m entre estaciones",
        ruido: "Alto",
        tiene_sombra: true,
        mejor_estacion: ["Invierno"],
        notas_honestas: "Pasarelas anchas con barandas, pero mucha gente y ruido cataratas; ir temprano fuera temporada.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        pet_friendly: false,
        imagenes: ["https://images.unsplash.com/photo-1534067783741-512d0bf041e2?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Lanín",
        slug: "lanin",
        ubicacion: "Neuquén",
        lat: -39.6500,
        lng: -71.4833,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Bastón", "Andador"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "200m circuitos accesibles",
        ruido: "Bajo",
        tiene_sombra: true,
        mejor_estacion: ["Verano"],
        notas_honestas: "Centros visitantes rampas, sillas senderismo disponibles; no todos senderos accesibles, pedir info.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1501854140884-074bf86ee911?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Nahuel Huapi",
        slug: "nahuel-huapi",
        ubicacion: "Bariloche, Río Negro/Neuquén",
        lat: -41.1335,
        lng: -71.3103,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo-Medio",
        movilidad: ["Bastón", "Andador"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: false,
        distancia_aprox: "300m miradores",
        ruido: "Medio",
        tiene_sombra: true,
        mejor_estacion: ["Verano"],
        notas_honestas: "Infraestructura adaptada, sillas senderismo; viento patagónico fuerte, elegir paseos cortos.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1623886561280-5b5840652618?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Los Glaciares",
        slug: "los-glaciares",
        ubicacion: "El Calafate, Santa Cruz",
        lat: -50.4833,
        lng: -73.0500,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Bastón", "Andador"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "200m pasarelas mirador",
        ruido: "Medio",
        tiene_sombra: false,
        mejor_estacion: ["Verano"],
        notas_honestas: "Pasarelas mirador Perito Moreno accesibles, sillas disponibles; frío y viento intensos.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1516972087532-6a6d6d45b409?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Tierra del Fuego",
        slug: "tierra-del-fuego",
        ubicacion: "Ushuaia, Tierra del Fuego",
        lat: -54.8333,
        lng: -68.4833,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo-Medio",
        movilidad: ["Silla", "Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "400m Bahía Lapataia",
        ruido: "Bajo",
        tiene_sombra: true,
        mejor_estacion: ["Verano"],
        notas_honestas: "Pasarelas accesibles costa y La Castorera; clima cambiante, viento fuerte.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1518098268026-4e14d6aae18c?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional El Palmar",
        slug: "el-palmar",
        ubicacion: "Entre Ríos",
        lat: -31.8667,
        lng: -58.2333,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo-Medio",
        movilidad: ["Bastón", "Andador"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "300m senderos",
        ruido: "Bajo",
        tiene_sombra: false,
        mejor_estacion: ["Otoño", "Primavera"],
        notas_honestas: "Sillas senderismo disponibles; mucho sol sin sombra, llevar protección.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Pre Delta",
        slug: "pre-delta",
        ubicacion: "Entre Ríos",
        lat: -32.1167,
        lng: -60.6333,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Silla", "Andador"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "200m senderos",
        ruido: "Bajo",
        tiene_sombra: true,
        mejor_estacion: ["Primavera", "Otoño"],
        notas_honestas: "Terreno bajo tranquilo, aves; mosquitos verano, excelente opción cerca.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Talampaya",
        slug: "talampaya",
        ubicacion: "La Rioja",
        lat: -29.7833,
        lng: -67.9833,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Bajo",
        movilidad: ["Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: true,
        distancia_aprox: "Vehicular + bajadas cortas",
        ruido: "Bajo",
        tiene_sombra: false,
        mejor_estacion: ["Otoño", "Invierno"],
        notas_honestas: "Mayoría vehicular, visual desde vehículo; sol fuerte, clima seco extremo.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    },
    {
        nombre: "Parque Nacional Sierra de las Quijadas",
        slug: "sierra-quijadas",
        ubicacion: "San Luis",
        lat: -32.5500,
        lng: -67.0167,
        costo: "Gratis con CUD",
        nivel_esfuerzo: "Medio",
        movilidad: ["Bastón"],
        tiene_rampa: true,
        tiene_banio: true,
        es_plano: false,
        distancia_aprox: "500m senderos adaptados",
        ruido: "Bajo",
        tiene_sombra: true,
        mejor_estacion: ["Primavera", "Otoño"],
        notas_honestas: "Sillas senderismo parque; agreste, mejor con acompañante y equipo.",
        fuente: "Declarado",
        estacion_actual: "Verano 2026",
        imagenes: ["https://images.unsplash.com/photo-1474044158699-59270e9b936e?auto=format&fit=crop&q=80&w=1080"],
        categoria: "Naturaleza"
    }
];

async function main() {
    console.log('Start seeding ...');

    // Clear existing data to avoid mess
    // await prisma.lugar.deleteMany(); 
    // Actually, upsert is safer if there are relations, but we want a clean state.
    // Given the user frustration, let's just update everything.

    for (const lugar of LUGARES) {
        const result = await prisma.lugar.upsert({
            where: { slug: lugar.slug },
            update: lugar,
            create: lugar,
        });
        console.log(`Upserted lugar: ${result.nombre} (ID: ${result.id})`);
    }
    console.log('Seeding finished.');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
